### PR TITLE
Added -ip flag to save new files in place (same folder as originals)

### PR DESCRIPTION
**Pull request by CodeAngry**
1.) Added -ip flag to save new files in place (same folder as originals).
In case names collide, a _ is appended to the file name.
2.) Added a basic method of testing custom command lines in the debugger.

### CODE REVIEW

**Comment by walbourn** [comment]
So the intent of the original design of ``texconv`` is that if you want the files to go the same logical, you can add a prefix or a post-fix with ``-px`` or ``-sx``.

**Comment by CodeAngry** [comment]
It's a fully optional feature. And I prefer to convert the files in place and then run a second tool that bundles them together into another format based on the folders where they are located. But finding them in their original location is much easier and makes more sense. And did I mention?, it's opt-in.

It's also been requested before so I'm definitely not the only one to need this:
https://github.com/Microsoft/DirectXTex/issues/104

Code change is simple, easy to follow. And this is not about intent of the tool, it's about this is about handling more use cases and allowing more customization.

**Comment by walbourn** [comment]
I respect your preference for workflow, but I think that [this](https://github.com/microsoft/DirectXTex/issues/200) might be a better general solution where you can reproduce a directory structure in a target folder

**Comment by walbourn** [comment]
The "in-place" approach is pretty dangerous in terms of potentially losing your original files. With the new ``-r:keep`` option, you should be able to keep any directory structure you want in place in the output directory. You can always set the output directory to your source directory if you want.

**Pull request closed without merging**
