### PR TITLE
Ignore CMake generated files

### PR DESCRIPTION
**Pull request by Akarinnnnn**

### CODE REVIEW

**Comment by walbourn** [comment]
In my use all the stuff ends up under ``/out`` so is already ignored..

**Comment by Akarinnnnn** [comment]
> In my use all the stuff ends up under /out so is already ignored..  

Well, I mean files in `CMakeFiles`, they are not ignoed.

**Comment by Akarinnnnn** [comment]
and these files
image

**Comment by walbourn** [comment]
None of those files end up in my directory when using CMake. They always end up in ``./out/..``

**Pull request closed without merging**
