### PR TITLE
Update DirectXTex.h

### PR DESCRIPTION
**Pull request by karurung**
'void*' to 'uint8_t*'

### CODE REVIEW

**Comment by walbourn** [comment]
``EncodeDDSHeader`` updates are missing.

**Comment by walbourn** [comment]
This PR needs updated to include the matching fixes to the cpp files.

```
DirectXTexDDS.cpp 
DirectXTexHDR.cpp
DirectXTexTGA.cpp
DirectXTexWIC.cpp
```
 
Please include these file changes in THIS PR and not in distinct ones as that is hard to test and will fail GitHub Action validation.

**Comment by karurung** [comment]
Sorry, I'm new to creating Pull Requests (PRs) and I'm not sure how to proceed.

**Comment by walbourn** [comment]
https://github.com/microsoft/DirectXTex/pull/538

**Pull request closed without merging**
